#!/bin/ksh

############################## standard interface to /sw tools
# Input:
#   Environment variables
#     SW_BLDDIR    current directory (PWD) minus /autofs/na1_ stuff
#     SW_ENVFILE   file to be sourced which has alternate prog environment
#                     only to be used in special circumstances
#     SW_WORKDIR   unique work dir that local script can use
# Output
#   Return code of 0=success or 1=failure 
##############################

if [ -z $SW_BLDDIR ]; then
  echo "Error: SW_BLDDIR not set!"
  exit 1
else
  cd $SW_BLDDIR
fi

if [ -z $SW_ENVFILE ]; then
  ### Set Environment (do not remove this line only change what is in between)
  . ${MODULESHOME}/init/ksh
  . ${SW_BLDDIR}/remodule
  ### End Environment (do not remove this line only change what is in between)
else
  . $SW_ENVFILE
fi

############################## app specific section
#  
set -o verbose
# clear out old installation to prevent potential libtool chmod 
# commands from failing when reinstalled by another person
rm -rf bin lib include status test.log $SRCDIR


#clear out status file since re-making
rm -f status

tar xf /sw/sources/$PACKAGE/$VERSION/$SRCDIR.tar.gz
cd $SRCDIR/src/milc-nsf/ks_imp_dyn2

# Make clean
make -f Make_mpi clean
touch ../libraries/Make_vanilla

#Make
make -f Make_mpi su3_rmd

if [[ ! -e su3_rmd ]] ; then
    echo "make failed"
    exit 1
fi

mkdir -p $SW_BLDDIR/bin
cp su3_rmd $SW_BLDDIR/bin

cd $SW_BLDDIR

############################### if this far, return 0
exit 0
