#!/bin/ksh

############################## standard interface to /sw tools
# Input:
#   Environment variables
#     SW_BLDDIR    current directory (PWD) minus /autofs/na1_ stuff
#     SW_ENVFILE   file to be sourced which has alternate prog environment
#                     only to be used in special circumstances
#     SW_WORKDIR   work dir that local script can use
# Output:
#   Return code of 0=success or 1=failure   or 2=job submitted
#
# Notes:
#   If this script is called from swtest, then swtest requires 
#   SW_WORKDIR to be set.  Then swtest adds a unique path to what 
#   user gave swtest (action+timestamp+build) and provides this
#   script with a uniquely valued SW_WORKDIR.  swtest will
#   automatically remove this unique workspace when retest is done.
##################################################################

# exit 3 is a signal to the sw infrastructure that this template has not 
# been updated; please delete it when ready

if [ -z $SW_BLDDIR ]; then
  echo "Error: SW_BLDDIR not set!"
  exit 1
else
  cd $SW_BLDDIR
fi

if [ -z $SW_ENVFILE ]; then
  ### Set Environment (do not remove this line only change what is in between)
  . ${MODULESHOME}/init/ksh
  . ${SW_BLDDIR}/remodule
  ### End Environment (do not remove this line only change what is in between)
else
  . $SW_ENVFILE
fi

############################## app specific section
#  
#clear out status file since re-testing
rm -f status 

cd $SW_WORKDIR

#-- Four things are required in the PBS script such that it can be followed
#   correctly by jenkins:
#   1. The PBS_JOBID (given upon submission with 'qsub') needs to be written
#      to the ${SW_BLDDIR}/.running file on submission
#   2. The main output of the test (i.e. typically "aprun" command output)
#      needs to be appended to ${SW_BLDDIR}/.running as the test runs
#   3. If the test succeed, the first line of $SW_BLDDIR/status file must be 
#      the string "verified"
#   4. ${SW_BLDDIR}/.running must be removed after the test completes
    

cat > ${PACKAGE}.pbs << EOF
#!/bin/bash
#PBS -N ${PACKAGE}
#PBS -j oe
#PBS -l nodes=2:ppn=32,walltime=30:00

set -o verbose
cd \$PBS_O_WORKDIR

module swap PrgEnv-cray PrgEnv-gnu
module add craype-hugepages2M

H5BIN=${SW_BLDDIR}/bin/hdf5Benchmark
aprun -n 12 \$H5BIN | tee ${PACKAGE}.log | tee -a ${SW_BLDDIR}/.running
#aprun -n 12 \$H5BIN | tee -a ${SW_BLDDIR}/.running

#-- Check result
if [ -e RadHyd3D_output_000000010.h5 ]; then
  echo "verified" > ${SW_BLDDIR}/status
else
  echo "unverified" > ${SW_BLDDIR}/status
fi

grep Performance ${PACKAGE}.log | awk '{print "YVALUE=",\$2}' \
  | sed 's/ //g' > ${SW_BLDDIR}/bandwidth

JOBID=\`echo \$PBS_JOBID | cut -d "." -f1 \`
chmod 775 ${SW_BLDDIR}/status
rm ${SW_BLDDIR}/.running
cat \${JOBID}.OU >> ${SW_BLDDIR}/test.log
cat ${PACKAGE}.log >> ${SW_BLDDIR}/test.log
chmod 664 ${SW_BLDDIR}/test.log
EOF


#submit job and touch .running file - marker to infrastructure that
qsub ${PACKAGE}.pbs 2>&1 > ${SW_BLDDIR}/.running

# qsub returns 0 on successful job launch, so if failure return 1
if [ $? -ne 0 ]; then
  echo "Error submitting job"
  cat ${SW_BLDDIR}/.running
  rm -f ${SW_BLDDIR}/.running
  exit 1
else
  echo "Job submitted"
  cat ${SW_BLDDIR}/.running
  exit 2
fi

cd ../

cd ../../

############################### if this far, return 0
exit 0
